// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShepardPies.Data;

#nullable disable

namespace ShepardPies.Migrations
{
    [DbContext(typeof(ShepardPiesDbContext))]
    [Migration("20241220045441_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c3aaeb97-d2ba-4a53-a521-4eea61e59b35",
                            Name = "Admin",
                            NormalizedName = "admin"
                        },
                        new
                        {
                            Id = "c4bbeb97-d3ba-4b53-b521-5ffa61e59b36",
                            Name = "Employee",
                            NormalizedName = "employee"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "75c96a18-e8e6-4cd0-8ea9-27afaff7a3ab",
                            Email = "admina@strator.comx",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEER3rKvnlElK4QUlfpxnk+LjoIqade1cwxiN6565m1rd6zNcJkqxN5ypmZr6baGzzg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f4f8cc37-e7eb-4a6e-8832-0250f74dd3fe",
                            TwoFactorEnabled = false,
                            UserName = "Administrator"
                        },
                        new
                        {
                            Id = "d6bc2e97-e1fc-4a2f-b112-6ff861e69c37",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "13ef7758-b64d-445c-957b-c02f70023aee",
                            Email = "employee1@company.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAECAvsoHef+dTM1YnIszI6ToT4YGpudUP19aWuvZ3k3a1ohDWpSh2ujKG3H+0+l23Zg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "480f5526-8f9c-4f19-bb82-c5895fbb334a",
                            TwoFactorEnabled = false,
                            UserName = "employee1"
                        },
                        new
                        {
                            Id = "a1bc2e97-e2fc-4a3f-b123-7ff861e69d38",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ef372ea8-4945-4495-897a-c9322765c288",
                            Email = "employee2@company.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEMbDvEW3n8lfT7ARzQtWwrG9RX624DjNobAM7c/jUsuDb1IAhAtZ3QngKqP3r3lf7w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9d09acb6-c112-4285-99e9-d9c1f3f75136",
                            TwoFactorEnabled = false,
                            UserName = "employee2"
                        },
                        new
                        {
                            Id = "b2cd3e97-f3dc-4b4f-b234-8ff861e69e39",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bd567098-acf8-4230-afb4-e37e896f34e4",
                            Email = "employee3@company.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEKHem/uInjODh5nt0SQg6mez37j2HOGHJSMhj9hgJoyUZJ235p96GNtZeOfD7Y3ITA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "65e21d22-7fa2-4f92-9606-e78bc3f1859d",
                            TwoFactorEnabled = false,
                            UserName = "employee3"
                        },
                        new
                        {
                            Id = "c3de4e97-g4ec-4c5f-b345-9ff861e69f40",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "39ec0884-d4e2-4930-a748-673304960b08",
                            Email = "employee4@company.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEJWcz3qYuO2cNpagP93TCRS9t4yEmXOyHPONXN3f0dZUN4RTr/B7HlaZuKfokj1/Ng==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e6dbdc03-98c0-4030-8a02-0a4d2d189d3e",
                            TwoFactorEnabled = false,
                            UserName = "employee4"
                        },
                        new
                        {
                            Id = "d4ef5e97-h5fc-4d6f-b456-aff861e69g41",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8f476dc0-a3a3-4a31-a067-c92ebb70a086",
                            Email = "employee5@company.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAELgzCfaGzfvZwCEmqBuwwoeAZpxGgFYa/AQbX7FxHN2Xcg4ZPYrUqL3FlEk+auv7kQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f558df9f-0c61-47cc-b3dd-2a661bf11db7",
                            TwoFactorEnabled = false,
                            UserName = "employee5"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            RoleId = "c3aaeb97-d2ba-4a53-a521-4eea61e59b35"
                        },
                        new
                        {
                            UserId = "d6bc2e97-e1fc-4a2f-b112-6ff861e69c37",
                            RoleId = "c4bbeb97-d3ba-4b53-b521-5ffa61e59b36"
                        },
                        new
                        {
                            UserId = "a1bc2e97-e2fc-4a3f-b123-7ff861e69d38",
                            RoleId = "c4bbeb97-d3ba-4b53-b521-5ffa61e59b36"
                        },
                        new
                        {
                            UserId = "b2cd3e97-f3dc-4b4f-b234-8ff861e69e39",
                            RoleId = "c4bbeb97-d3ba-4b53-b521-5ffa61e59b36"
                        },
                        new
                        {
                            UserId = "c3de4e97-g4ec-4c5f-b345-9ff861e69f40",
                            RoleId = "c4bbeb97-d3ba-4b53-b521-5ffa61e59b36"
                        },
                        new
                        {
                            UserId = "d4ef5e97-h5fc-4d6f-b456-aff861e69g41",
                            RoleId = "c4bbeb97-d3ba-4b53-b521-5ffa61e59b36"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ShepardPies.Models.Cheese", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cheeses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Buffalo Mozzarella"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Four Cheese"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Vegan"
                        },
                        new
                        {
                            Id = 4,
                            Name = "None"
                        });
                });

            modelBuilder.Entity("ShepardPies.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DriverId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OrderPlacedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("Tip")
                        .HasColumnType("numeric");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderPlacedOn = new DateTime(2024, 12, 15, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Tip = 5.00m,
                            UserProfileId = 2
                        },
                        new
                        {
                            Id = 2,
                            DriverId = 4,
                            OrderPlacedOn = new DateTime(2024, 12, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 2
                        },
                        new
                        {
                            Id = 3,
                            DriverId = 5,
                            OrderPlacedOn = new DateTime(2024, 12, 17, 18, 45, 0, 0, DateTimeKind.Unspecified),
                            Tip = 7.00m,
                            UserProfileId = 3
                        });
                });

            modelBuilder.Entity("ShepardPies.Models.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CheeseId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("SauceId")
                        .HasColumnType("integer");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CheeseId");

                    b.HasIndex("OrderId");

                    b.HasIndex("SauceId");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CheeseId = 1,
                            OrderId = 1,
                            Price = 10.00m,
                            SauceId = 1,
                            Size = "Small"
                        },
                        new
                        {
                            Id = 2,
                            CheeseId = 2,
                            OrderId = 1,
                            Price = 12.00m,
                            SauceId = 2,
                            Size = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            CheeseId = 3,
                            OrderId = 2,
                            Price = 15.00m,
                            SauceId = 3,
                            Size = "Large"
                        },
                        new
                        {
                            Id = 4,
                            CheeseId = 2,
                            OrderId = 3,
                            Price = 15.00m,
                            SauceId = 1,
                            Size = "Large"
                        });
                });

            modelBuilder.Entity("ShepardPies.Models.PizzaTopping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PizzaId")
                        .HasColumnType("integer");

                    b.Property<int>("ToppingId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PizzaId");

                    b.HasIndex("ToppingId");

                    b.ToTable("PizzaToppings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PizzaId = 1,
                            ToppingId = 1
                        },
                        new
                        {
                            Id = 2,
                            PizzaId = 1,
                            ToppingId = 2
                        },
                        new
                        {
                            Id = 3,
                            PizzaId = 2,
                            ToppingId = 3
                        },
                        new
                        {
                            Id = 4,
                            PizzaId = 2,
                            ToppingId = 4
                        },
                        new
                        {
                            Id = 5,
                            PizzaId = 3,
                            ToppingId = 5
                        },
                        new
                        {
                            Id = 6,
                            PizzaId = 4,
                            ToppingId = 6
                        });
                });

            modelBuilder.Entity("ShepardPies.Models.Sauce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sauces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Marinara"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Arrabbiata"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Garlic White"
                        },
                        new
                        {
                            Id = 4,
                            Name = "None"
                        });
                });

            modelBuilder.Entity("ShepardPies.Models.Topping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Toppings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sausage",
                            Price = 0.50m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pepperoni",
                            Price = 0.50m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mushroom",
                            Price = 0.50m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Onion",
                            Price = 0.50m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Green Pepper",
                            Price = 0.50m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Black Olive",
                            Price = 0.50m
                        },
                        new
                        {
                            Id = 7,
                            Name = "Basil",
                            Price = 0.50m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Extra Cheese",
                            Price = 0.50m
                        });
                });

            modelBuilder.Entity("ShepardPies.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "101 Main Street",
                            FirstName = "Admina",
                            IdentityUserId = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            LastName = "Strator"
                        },
                        new
                        {
                            Id = 2,
                            Address = " 220 High Street",
                            FirstName = "Tom",
                            IdentityUserId = "d6bc2e97-e1fc-4a2f-b112-6ff861e69c37",
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 3,
                            Address = "123 Oak Street",
                            FirstName = "Emily",
                            IdentityUserId = "a1bc2e97-e2fc-4a3f-b123-7ff861e69d38",
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 4,
                            Address = "456 Maple Avenue",
                            FirstName = "Michael",
                            IdentityUserId = "b2cd3e97-f3dc-4b4f-b234-8ff861e69e39",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 5,
                            Address = "789 Pine Lane",
                            FirstName = "Sarah",
                            IdentityUserId = "c3de4e97-g4ec-4c5f-b345-9ff861e69f40",
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 6,
                            Address = "321 Elm Road",
                            FirstName = "Robert",
                            IdentityUserId = "d4ef5e97-h5fc-4d6f-b456-aff861e69g41",
                            LastName = "Brown"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShepardPies.Models.Order", b =>
                {
                    b.HasOne("ShepardPies.Models.UserProfile", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId");

                    b.HasOne("ShepardPies.Models.UserProfile", "OrderTaker")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("OrderTaker");
                });

            modelBuilder.Entity("ShepardPies.Models.Pizza", b =>
                {
                    b.HasOne("ShepardPies.Models.Cheese", "Cheese")
                        .WithMany()
                        .HasForeignKey("CheeseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShepardPies.Models.Order", "Order")
                        .WithMany("Pizzas")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShepardPies.Models.Sauce", "Sauce")
                        .WithMany()
                        .HasForeignKey("SauceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cheese");

                    b.Navigation("Order");

                    b.Navigation("Sauce");
                });

            modelBuilder.Entity("ShepardPies.Models.PizzaTopping", b =>
                {
                    b.HasOne("ShepardPies.Models.Pizza", "Pizza")
                        .WithMany("Toppings")
                        .HasForeignKey("PizzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShepardPies.Models.Topping", "Topping")
                        .WithMany()
                        .HasForeignKey("ToppingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pizza");

                    b.Navigation("Topping");
                });

            modelBuilder.Entity("ShepardPies.Models.UserProfile", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("ShepardPies.Models.Order", b =>
                {
                    b.Navigation("Pizzas");
                });

            modelBuilder.Entity("ShepardPies.Models.Pizza", b =>
                {
                    b.Navigation("Toppings");
                });
#pragma warning restore 612, 618
        }
    }
}
